### PR TITLE
feat: array image Name

### PR DESCRIPTION
**Pull request by reslear**
Initially, I made it a function in options (cb(resultName)), then searched the name matrix. Later, I opted to pre-prepare an array with the necessary names. Also improved duplicate name checking.

before: 

```ts
const images = ['https://placehold.co/600x400', 'https://placehold.co/100x200']
const loads = await imgdl(images)
// result 600x400.jpg, 100x200.jpg
// 
```

after:

```ts
const images = [
  { url: 'https://placehold.co/600x400', name: 'myimage'}, 
  { url: 'https://placehold.co/100x200', name: 'fav'}
]

const loads = await imgdl(images)
// result myimage.jpg, fav.jpg
```

### CODE REVIEW

**Comment by reslear** [comment]
@fityannugroho

**Comment by fityannugroho** [comment]
Can you update the test please @reslear?

**Comment by reslear** [comment]
hi is @fityannugroho actual write test?

**Comment by fityannugroho** [comment]
> Can you update the test please @reslear?

> hi is @fityannugroho actual write test after big refactor ?

UPDATE:
Yes, I have revamp the API and add some features, including the [Overwrite Prevention](https://github.com/fityannugroho/img-dl?tab=readme-ov-file#overwrite-prevention) feature that ensure there are no duplicate image names by default. So your changes for duplicate name checking is no needed anymore.

Related with your feature request to set specific name for each download, I think it's better to provides **URL-level options** feature that using object contains image url as the key, and the `ImageOptions` as the values. I have create a discussion for this in https://github.com/fityannugroho/img-dl/discussions/19. Feel free to share your thoughts @reslear :)

**Comment by fityannugroho** [comment]
This issus has been resolved by PR #20

**Pull request closed without merging**
